background_opacity 0.70
dynamic_background_opacity yes
# foreground            #cccccc
# cursor                #ffffff
# selection_background  #ffffff
# selection_foreground  #012456

# Font settings matching modern Windows terminals
font_family      Jetbrains Mono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        11.0

#window_padding_width     12
hide_window_decorations  yes
confirm_os_window_close  0

#active_border_color     #0078d4
#inactive_border_color   #202020
draw_minimal_borders    yes

cursor_trail 1
cursor_trail_decay 0.1 0.5
# Change the shape (options: block, beam, underline)
cursor_shape beam

# Shape to use when you switch to another app window (options: block, beam, underline, hollow)
cursor_shape_unfocused hollow

# Make the cursor blink smoothly using a CSS-style easing animation
cursor_blink_interval 0.5 ease-in-out



